### ISSUE TITLE
ImportError: libgfortran.so.1

### ISSUE THREAD

**Issue by ShwanMario** [gramuah/ccnn#5]
Hello~And sorry for bothering you.

I encountered some problem while duplicate your demo when I run $ ./tools/demo.sh

And the error information goes like this:

Traceback (most recent call last):
  File "src/test.py", line 24, in <module>
    import scipy.io as sio
  File "/home/chen/anaconda3/envs/caffe/lib/python2.7/site-packages/scipy/io/__init__.py", line 85, in <module>
    from .matlab import loadmat, savemat, whosmat, byteordercodes
  File "/home/chen/anaconda3/envs/caffe/lib/python2.7/site-packages/scipy/io/matlab/__init__.py", line 13, in <module>
    from .mio import loadmat, savemat, whosmat
  File "/home/chen/anaconda3/envs/caffe/lib/python2.7/site-packages/scipy/io/matlab/mio.py", line 12, in <module>
    from .miobase import get_matfile_version, docfiller
  File "/home/chen/anaconda3/envs/caffe/lib/python2.7/site-packages/scipy/io/matlab/miobase.py", line 22, in <module>
    from scipy.misc import doccer
  File "/home/chen/anaconda3/envs/caffe/lib/python2.7/site-packages/scipy/misc/__init__.py", line 49, in <module>
    from scipy.special import comb, factorial, factorial2, factorialk
  File "/home/chen/anaconda3/envs/caffe/lib/python2.7/site-packages/scipy/special/__init__.py", line 601, in <module>
    from ._ufuncs import *
ImportError: libgfortran.so.1: cannot open shared object file: No such file or directory
Time in seconds: 0

Could you help me solve this problem?

I would be very grateful if you reply me soon!

**Comment by roleiland** [comment]
Hi Mario,


This is a problem of your libraries. Try to search the error you get in the web before. I have pasted your error in Google and I found:


https://github.com/menpo/landmarkerio-server/issues/23



I hope it helps.


Best.

[https://avatars1.githubusercontent.com/u/4290551?s=400&v=4]<https://github.com/menpo/landmarkerio-server/issues/23>

ImportError: libgfortran.so.1: cannot open shared object ...<https://github.com/menpo/landmarkerio-server/issues/23>
github.com
GitHub is where people build software. More than 27 million people use GitHub to discover, fork, and contribute to over 80 million projects.



________________________________
